name: mutation_runner
description: A new flutter project.
dependencies:
  shelf: any
  shelf_static: any
  shelf_route: any
  path: any
  flutter_tools:
    path: ../../GitRepos/flutter/packages/flutter_tools/

  flutter:
     path: ../../GitRepos/flutter/packages/flutter/

  vm_service_lib: any
