name: flutter_server
description: A new flutter project.
dependencies:
  shelf: any
  shelf_static: any
  shelf_route: any
  path: any
  flutter_tools:
    path: /Users/lukechurch/GitRepos/flutter/packages/flutter_tools

  # flutter:
    # path: ../../flutter/packages/flutter
